---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-brewmaster-backend
      vars:
        backend_repo_version: develop
        backend_environments:
          DATABASE_PASSWORD: brewmaster
          DATABASE_USER: postgres
          DATABASE_NAME: brewmaster
          DATABASE_HOST: timescaledb
